### ISSUE TITLE
Cleanup of temporary Linode

### ISSUE THREAD

**Issue by akerl** [linode/packer-builder-linode#11]
This might be my misunderstanding of how Packer functions, but the image creation here seems to leave behind a temporary Linode. Ideally, I'd like to have this Linode be deleted after the image is created.

Is there a clean way to do that in the Packer builder?

**Comment by displague** [comment]
https://github.com/linode/packer-builder-linode/blob/master/linode/step_create_linode.go#L91

Assuming the Cleanups are called in reverse order of the steps defined in the builder.go file, this should already be happening.

I will verify that this is the case.

**Comment by displague** [comment]
```
$ LINODE_TOKEN=$(daily-token.sh) packer build -var "linode-token=$LINODE_TOKEN" test/fixtures/builder-linode/minimal.json
linode output will be in this color.

==> linode: Running builder ...
==> linode: Creating temporary SSH key for instance...
==> linode: Creating Linode...
==> linode: Using ssh communicator to connect: 45.33.119.164
==> linode: Waiting for SSH to become available...
==> linode: Connected to SSH!
==> linode: Provisioning with shell script: /var/folders/_5/pf50rr6d3q34j1bbcg_9hfpm0000gn/T/packer-shell794412469
==> linode: Shutting down Linode...
==> linode: Creating image...
Build 'linode' finished.

==> Builds finished. The artifacts of successful builds are:
--> linode: Linode image: packerbats-minimal-image-1554151431 (private/5998905)
```

I checked my account and there was no temporary Linode left behind.

Can you reproduce this problem?

**Comment by displague** [comment]
It would be helpful if the output included "Deleting Linode"

**Comment by akerl** [comment]
Huh, yea, I can't reproduce it now. No idea what happened :(
