### ISSUE TITLE
packer-builder-linode vs linode imaging

### ISSUE THREAD

**Issue by dm17** [linode/packer-builder-linode#14]
Maybe we can have some discussion to help linode newbies get started...

One option is to install a distro via Linode's default images. Then we can modify that and create a base image. How does that compare to using packer? Also I'd like to know the difference between building a linux distro with packer for linode and building an AMI with AWS's AMI builder... They're analogous, yes?

**Comment by displague** [comment]
Packer-builder-linode is a plugin for Packer that allows you to create Linode Images reproducibly.

Packer allows you to script your base image modifications.  Your custom image is then repeatable and reproducible.  For example, a CI/CD tool like CircleCI or Travis could rebuild your image whenever you make an update to the repo with the Packer configuration.  Or you could schedule this to run daily and your deployments that use this image will always start with the most recent updates.

Here are some examples:
* https://github.com/linode/packer-builder-linode/blob/master/test/fixtures/builder-linode/minimal.json
* https://github.com/armorfret/packer-linode-wireguard
* https://github.com/stvnjacobs/packer-templates-linode

Comparing this to the Packer AWS AMI Builder, this plugin is most similar to the amazon-ebs builder listed here: https://www.packer.io/docs/builders/amazon.html

**Comment by dm17** [comment]
Interesting... So this would allow you to have a build process with almost 100% identical code between, say, Linode and Vultr - correct? I see this packer project for Vultr: https://github.com/dradtke/packer-builder-vultr

It looks like there are a bunch of packer-linode projects out there - so I'll have to choose some criteria to pick one and stick with it (likely the most maintained).

**Comment by displague** [comment]
@dm17 This project was started with @dradtke's packer-builder-linode repo.  After it reached a certain maturity level it was moved to the Linode org (here). (Thanks again, @dradtke!) 

And then, this project was merged into Packer itself.

Ultimately the project to use should be Packer itself (without the need for the additional plugins), once the next version of Packer ships with the `linode` builder bundled. This project may continue to be a proving ground for additional Packer plugins for Linode (or those could just happen upstream, time will tell).

https://github.com/hashicorp/packer/pull/7508
