### ISSUE TITLE
Change LICENSE to MPL/2 for compatibility with upstream Packer project

### ISSUE THREAD

**Issue by displague** [linode/packer-builder-linode#8]
Adopt the parent project license so that this plugin may be included in the parent project:

https://github.com/hashicorp/packer/blob/master/LICENSE

**Comment by Ajibola** [comment]
I'm happy for my contributions to be re-licensed to MPL/2

**Comment by dradtke** [comment]
I'm 👍 on my contributions being re-licensed to MPL/2.

**Comment by stvnjacobs** [comment]
I give permission that my contributions to be re-licensed to MPL/2.

**Comment by displague** [comment]
I give my permission to move this to MPL/2 too.

Thanks everyone!
